from __future__ import annotations

EXPANSION_STATUS_PENDING = "PENDING"
EXPANSION_STATUS_IN_PROGRESS = "IN_PROGRESS"
EXPANSION_STATUS_COMPLETED = "COMPLETED"
EXPANSION_STATUS_RETRYABLE = "RETRYABLE"
EXPANSION_STATUS_BLOCKED = "BLOCKED"
EXPANSION_STATUS_SKIPPED = "SKIPPED"
EXPANSION_STATUS_EXHAUSTED = "EXHAUSTED"

EXPANSION_STATUSES = (
    EXPANSION_STATUS_PENDING,
    EXPANSION_STATUS_IN_PROGRESS,
    EXPANSION_STATUS_COMPLETED,
    EXPANSION_STATUS_RETRYABLE,
    EXPANSION_STATUS_BLOCKED,
    EXPANSION_STATUS_SKIPPED,
    EXPANSION_STATUS_EXHAUSTED,
)

ERROR_CATEGORY_RATE_LIMIT = "RATE_LIMIT"
ERROR_CATEGORY_PLAN_RESTRICTED = "PLAN_RESTRICTED"
ERROR_CATEGORY_NETWORK = "NETWORK"
ERROR_CATEGORY_NOT_FOUND = "NOT_FOUND"
ERROR_CATEGORY_TEMPORARY = "TEMPORARY"
ERROR_CATEGORY_PERMANENT = "PERMANENT"
ERROR_CATEGORY_DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
ERROR_CATEGORY_PROVIDER_ERROR = "PROVIDER_ERROR"

STOP_REASON_BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
STOP_REASON_RATE_LIMIT = "RATE_LIMIT"
STOP_REASON_QUEUE_EMPTY = "QUEUE_EMPTY"
STOP_REASON_SAFETY_CAP = "SAFETY_CAP"
STOP_REASON_ERROR_THRESHOLD = "ERROR_THRESHOLD"
STOP_REASON_ALREADY_RAN_TODAY = "ALREADY_RAN_TODAY"
STOP_REASON_BACKPRESSURE_RETRY_WAIT = "BACKPRESSURE_RETRY_WAIT"
STOP_REASON_IN_PROGRESS_EXIT = "IN_PROGRESS_EXIT"
STOP_REASON_DISCOVERY_SOURCE_ERROR = "DISCOVERY_SOURCE_ERROR"

ORCHESTRATION_PARTICIPATION_ONLY = "PARTICIPATION_ONLY"
ORCHESTRATION_DISCOVERY_AND_PARTICIPATION = "DISCOVERY_AND_PARTICIPATION"
ORCHESTRATION_BACKPRESSURE_WAIT = "BACKPRESSURE_WAIT"
ORCHESTRATION_IN_PROGRESS_EXIT = "IN_PROGRESS_EXIT"
ORCHESTRATION_ALREADY_RAN_TODAY = "ALREADY_RAN_TODAY"
ORCHESTRATION_NO_NEW_DISCOVERY = "NO_NEW_DISCOVERY"

DISCOVERY_CYCLE_DECISIONS = frozenset(
    {
        ORCHESTRATION_DISCOVERY_AND_PARTICIPATION,
        ORCHESTRATION_NO_NEW_DISCOVERY,
    }
)

PROVIDER_FMP = "fmp"
PROVIDER_SEC = "sec"
